@t{@ref{Verb}@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ref{Adverb}@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ref{Noun,Type}@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ref{System}}@*
@t{:@ @ @ @ x@ @ @ @ @ @ @ @ @ @ y@ @ @ @ @ @ @ @ @ @ f/@ @ @ref{scan,over}@ @ c/@ @ +@ref{join}@ @ @ref{char}@ "@ ab"@ @ @ @ @ @ @ @ \l@ a.k}@*
@t{+@ @ @ @ @ref{flip}@ @ @ @ @ @ @ @ref{plus}@ @ @ @ @ @ @ f\@ @ @ref{scan}@ @ c\@ @ +@ref{split}@ @ref{name}@ ``ab@ @ @ @ @ @ @ @ @ \t:n@ x}@*
@t{-@ @ @ @ @ref{negate}@ @ @ @ @ @ref{minus}@ @ @ @ @ @ f'@ @ @ref{each}@ @ v'@ @ +has@ @ @ @ref{int}@ @ 0@ 2@ 3@ @ @ @ @ @ @ @ \u:n@ x}@*
@t{*@ @ @ @ @ref{first}@ @ @ @ @ @ @ref{times}@ @ @ @ @ @ f':@ @ref{eachp}@ v':@ +bin@ @ @ @ref{flt}@ @ 0@ 2@ 3.@ @ @ @ @ @ @ \v}@*
@t{%@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ref{divide}@ @ @ @ @ f/:@ @ref{eachr}@ ([n;]f)/:@ @ @ref{date}@ 2001.01.01@ @ @ .z.d}@*
@t{&@ @ @ @ @ref{where}@ @ @ @ @ @ @ref{min/and}@ @ @ @ f\:@ @ref{eachl}@ ([n;]f)\:@ @ @ref{time}@ 12:34:56.789@ .z.t}@*
@t{|@ @ @ @ @ref{reverse}@ @ @ @ @ref{max/or}}@*
@t{<@ @ @ @ @ref{asc}@ @ @ @ @ @ @ @ @ref{less}}@*
@t{>@ @ @ @ @ref{asc,dsc}@ @ @ @ @ @ @ @ @ref{less,more}}@*
@t{=@ @ @ @ @ref{group}@ @ @ @ @ @ @ref{equal}@ @ @ @ @ @ @ref{I/O}}@*
@t{~@ @ @ @ @ref{not}@ @ @ @ @ @ @ @ @ref{match}@ @ @ @ @ @ 0:@ @ @ref{r line,r}/@ref{w line,w}@ line@ @ @ @ @ @ @ @ @ Class@ @ @ @ @ @ @ @ @ @ @ @ @ \f}@*
@t{!@ @ @ @ @ref{enum}@ @ @ @ @ @ @ @ref{key}@ @ @ @ @ @ @ @ 1:@ @ @ref{r byte,r}/@ref{w byte,w}@ byte@ @ @ @ @ @ @ @ @ @ref{List}@ (2;3.4;`c)@ @ @ \ft@ x}@*
@t{,@ @ @ @ @ref{enlist}@ @ @ @ @ @ref{cat}@ @ @ @ @ @ @ *2:@ @ r/w@ data@ @ @ @ @ @ @ @ @ @ref{Dictionary,Dict}@ [a:2;b:`c]@ @ @ \fl@ x}@*
@t{^@ @ @ @ @ref{sort}@ @ @ @ @ref{[f]cut}@ @ @ @ @ @ @ *3:@ @ k-ipc@ set@ @ @ @ @ @ @ @ @ref{User Functions,Func}@ @{[a;b]a+b@}@ @ @ \fc@ x}@*
@t{#@ @ @ @ count@ @ @ @ref{[f]take}@ @ @ @ @ @ *4:@ @ https@ get@ @ @ @ @ @ @ @ @ref{Expression,Expr}@ :a+b@ @ @ @ @ @ @ @ @ \cd@ [d]}@*
@t{_@ @ @ @ @ref{floor}@ @ @ @ref{[f]drop}}@*
@t{$@ @ @ @ @ref{string}@ @ @ @ @ @ref{cast}@ @ @ @ @ @ @ $[b;t;f]@ @ref{cond,Control}@ @ @ @ @ @ref{Tables,Table}}@*
@t{?@ @ @ @ @ref{unique+}@ @ @ @ @ref{find+}@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ t:[[]i:2@ 3;f:3@ 4.;s:`a`b]}@*
@t{@@@ @ @ @ @ref{type}@ @ @ @ @ref{[f]at}@ @ @ @ @ @ @ @ @ @@[r;i;f[;y]]@ @ref{amend}@ @ @ @ref{utable}@ [[b:..]a:..]}@*
@t{.@ @ @ @ @ref{value}@ @ @ @ref{[f]dot}@ @ @ @ @ @ @ @ .[r;i;f[;y]]@ @ref{dmend}@ @ @ @ref{xtable}@ `..![[]a:..]}@*
@t{\\@ @ @ exit@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ /@ comment@ @ @ @ @ @ @ @ @ @ @ [if@ do@ while]}@*
@t{}@*
@t{@ref{select}[C]@{count@ first@ last@ sum@ min@ max@ *[avg@ var@ dev@ med@ ..]@}from@ T@ where@ B}@*
@t{@ref{update}@ C@ from@ T@ where@ B;@ @ref{delete}@ from@ T@ where@ B;@ @ref{key}@ @ref{unkey}@ @ref{meta}@ @ref{in}@ @ref{bin}@  @ref{within}}@*
@t{@ref{exp}@ @ref{log}@ @ref{sin}@ @ref{cos}@ @ref{sqr}@ @ref{sqr}t@ @ref{div}@ @ref{mod}@ @ref{bar};@ @ref{topX,top}@ @ref{freq}@ @ref{msum}@ @ref{mavg}@ @ref{sums}@ @ref{deltas}@ @ref{prm}@ @ref{cmb}}@*
